backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "faq"
    label: "FAQ"
    folder: "src/pages/faq"
    create: true
    identifier_field: question
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "faq",
        }
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          options: ["care", "geriatrics", "mobile care"],
          multiple: true,
        }
